#ifndef ISA_VARIABLES_H
#define ISA_VARIABLES_H

#define MAX_ANGLE_DIFFERENCE 5.0
#define NUMBER_OF_INITIAL_SAMPLES 5
#define FORWARD_POWER 100
#define TURNING_POWER 100
#define OBSTACLE_DISTANCE_FRONT 15
#define OBSTACLE_DISTANCE_SIDE 45
#define SOUND_SENSOR_BUFFER_SIZE 20
#define SERIAL_PORT_BUFFER_SIZE 64


#define NORTH_DIR 70
#define EAST_DIR 170
#define SOUTH_DIR -100
#define WEST_DIR -22

#define LEFT_DIR -1
#define RIGHT_DIR 1

#endif
